require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")


platform :ios, '12.0'

require 'json'
podfile_properties = JSON.parse(File.read('./Podfile.properties.json')) rescue {}

target 'Gurucan' do
  use_expo_modules!
  config = use_native_modules!

  use_react_native!(
        :path => config[:reactNativePath],
        :hermes_enabled => podfile_properties['expo.jsEngine'] == 'hermes'
      )

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!
  # use_flipper!({ 'Flipper' => '0.74.0' })
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'OneSignalNotificationServiceExtension' do
  #only copy below line
  pod 'OneSignal', '>= 2.11.2', '< 3.0'
end
